import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val constraintlayout: String = "2.0.0-beta2"

  const val core_ktx: String = "1.2.0-alpha03"

  const val androidx_databinding: String = "3.5.0-rc02" // available: "3.6.0-alpha09"

  const val lifecycle_extensions: String = "2.2.0-alpha03"

  const val androidx_navigation: String = "2.2.0-alpha01"

  const val espresso_core: String = "3.3.0-alpha02"

  const val androidx_test_runner: String = "1.3.0-alpha02"

  const val aapt2: String = "3.5.0-rc02-5435860" // available: "3.6.0-alpha09-5720371"

  const val com_android_tools_build_gradle: String = "3.5.0-rc02" // available: "3.6.0-alpha09"

  const val lint_gradle: String = "26.5.0-rc02" // available: "26.6.0-alpha09"

  const val crashlytics: String = "2.10.1"

  const val play_services_auth: String = "17.0.0"

  const val material: String = "1.1.0-alpha09"

  const val com_google_api_client: String = "1.23.0" // available: "1.30.2"

  const val google_api_services_drive: String = "v3-rev110-1.23.0"
       // available: "v3-rev20190620-1.30.1"

  const val gson: String = "2.8.5"

  const val firebase_analytics: String = "17.1.0" // available: "17.2.0"

  const val firebase_auth: String = "19.0.0"

  const val firebase_core: String = "17.1.0" // available: "17.2.0"

  const val google_services: String = "4.2.0" // available: "4.3.1"

  const val leakcanary_android: String = "2.0-beta-3"

  const val com_squareup_sqldelight: String = "1.1.4" // available: "1.2.0"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

  const val io_fabric_tools_gradle: String = "1.31.0"

  const val io_realm: String = "5.14.0"

  const val junit: String = "4.13-beta-3"

  const val anko: String = "0.10.8"

  const val org_jetbrains_kotlin: String = "1.3.50"

  const val se_patrikerdes_use_latest_versions_gradle_plugin: String = "0.2.12"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6.1"

  const val gradleCurrentVersion: String = "5.6"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
